name: Test and deploy to development
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js Latest
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: |
          npm ci
      - name: Run lint check
        run: |
          npm run test
